using System.Collections;
using UnityEngine;
using UnityEngine.SceneManagement;
using UnityEngine.UI;
using UnityEngine.EventSystems; // EventSystemï¿½ÌQï¿½ï¿½

public class MGameOver : MonoBehaviour
{
    public Text gameOverText;
    private static string messageToDisplay;
    public Button Restartbuttons; // ï¿½{ï¿½^ï¿½ï¿½ï¿½Ì”zï¿½ï¿½ï¿½Inspectorï¿½Åİ’ï¿½
    public Button Titlebuttons; // ï¿½{ï¿½^ï¿½ï¿½ï¿½Ì”zï¿½ï¿½ï¿½Inspectorï¿½Åİ’ï¿½
    private int selectedIndex = 0; // ï¿½Iï¿½ğ’†‚Ìƒ{ï¿½^ï¿½ï¿½ï¿½Cï¿½ï¿½ï¿½fï¿½bï¿½Nï¿½X

    void Start()
    {
        //Audio.GetInstance().StopLoopSound();
        deadmes(messageToDisplay);
        Audio.GetInstance().StopLoopSound();

        //// ï¿½Åï¿½ï¿½É‘Iï¿½ï¿½ï¿½ï¿½ï¿½ï¿½{ï¿½^ï¿½ï¿½ï¿½ï¿½İ’ï¿½
        //if (buttons.Length > 0)
        //{
        //    EventSystem.current.SetSelectedGameObject(buttons[0].gameObject);
        //}
        Restartbuttons.Select();
    }

    void Update()
    {
        // ï¿½Iï¿½ï¿½ï¿½ï¿½Ô‚Ì•ÏXï¿½ï¿½EventSystemï¿½ÉˆË‘ï¿½ï¿½ï¿½ï¿½é‚½ï¿½ßAï¿½Rï¿½[ï¿½hï¿½ï¿½ï¿½Åè“®ï¿½ï¿½ï¿½ï¿½Í•sï¿½vï¿½Å‚ï¿½
    }


    public void MainGameScene()
    {
        Scene.GetInstance().MainGame();
    }
    public void TitleGameScene()
    {
        Scene.GetInstance().TitleGame();
    }

    // ï¿½ï¿½ï¿½bï¿½Zï¿½[ï¿½Wï¿½ï¿½İ’è‚·ï¿½éƒï¿½\ï¿½bï¿½hï¿½iï¿½ï¿½ï¿½ÌƒVï¿½[ï¿½ï¿½ï¿½ï¿½ï¿½çƒï¿½bï¿½Zï¿½[ï¿½Wï¿½ï¿½İ’è‚·ï¿½ï¿½Û‚ÉŒÄ‚Ñoï¿½ï¿½ï¿½j
    public static void SetMessage(string mes)
    {
        messageToDisplay = mes;
    }

    // ï¿½ï¿½ï¿½bï¿½Zï¿½[ï¿½Wï¿½ï¿½\ï¿½ï¿½ï¿½ï¿½ï¿½éƒï¿½\ï¿½bï¿½h
    public void deadmes(string mes)
    {
        if (gameOverText != null)
        {
            gameOverText.text = mes;
        }
        else
        {
            Debug.LogWarning("gameOverText ï¿½ï¿½ï¿½ï¿½ï¿½è“–ï¿½Ä‚ï¿½ï¿½Ä‚ï¿½ï¿½Ü‚ï¿½ï¿½ï¿½B");
        }
    }
}
